# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

MRC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe
AS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\ml64.exe
CXX=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe
CC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe
CU=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc

LD=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe
CULD=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc
SH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe
AR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe

D3DRender_CXXFLAGS=/EHsc -nologo -Ox -fp:fast -std:c++17 -ID3DRender /utf-8 -DNDEBUG
D3DRender_LDFLAGS=-nologo -dynamicbase -nxcompat -machine:x64 /opt:ref /opt:icf

default:  D3DRender

all:  D3DRender

.PHONY: default all  D3DRender

D3DRender: build\windows\x64\release\D3DRender.exe
build\windows\x64\release\D3DRender.exe: build\.objs\D3DRender\windows\x64\release\D3DRender\main.cpp.obj
	@echo linking.release D3DRender.exe
	-@mkdir build\windows\x64\release > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe" $(D3DRender_LDFLAGS) -out:build\windows\x64\release\D3DRender.exe build\.objs\D3DRender\windows\x64\release\D3DRender\main.cpp.obj > build/.build.log 2>&1

build\.objs\D3DRender\windows\x64\release\D3DRender\main.cpp.obj: D3DRender\main.cpp
	@echo compiling.release D3DRender\main.cpp
	-@mkdir build\.objs\D3DRender\windows\x64\release\D3DRender > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c $(D3DRender_CXXFLAGS) -Fobuild\.objs\D3DRender\windows\x64\release\D3DRender\main.cpp.obj D3DRender\main.cpp > build/.build.log 2>&1

clean:  clean_D3DRender

clean_D3DRender: 
	@del /F /Q build\windows\x64\release\D3DRender.exe > NUL 2>&1 || rmdir /S /Q build\windows\x64\release\D3DRender.exe > NUL 2>&1
	@del /F /Q build\windows\x64\release\D3DRender.pdb > NUL 2>&1 || rmdir /S /Q build\windows\x64\release\D3DRender.pdb > NUL 2>&1
	@del /F /Q build\.objs\D3DRender\windows\x64\release\D3DRender\main.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\D3DRender\windows\x64\release\D3DRender\main.cpp.obj > NUL 2>&1

